import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Eye, EyeOff, ImagePlus, LogOut, Plus, Save, Trash2, XCircle } from 'lucide-react';
import type { Vehicle } from '../../data/vehicles';
import { vehicles as seedVehicles } from '../../data/vehicles';

function ImagePreview({ src, label, onBroken }: { src: string; label: string; onBroken?: () => void }) {
  const [state, setState] = useState<'loading' | 'ok' | 'broken'>(src ? 'loading' : 'broken');
  useEffect(() => setState(src ? 'loading' : 'broken'), [src]);
  if (!src || state === 'broken') return <div className="admin-image-preview admin-image-preview--broken"><XCircle size={18} /><span>{label}<small>Invalid or unavailable image URL</small></span></div>;
  return <div className="admin-image-preview"><img src={src} alt={label} onLoad={() => setState('ok')} onError={() => { setState('broken'); onBroken?.(); }} />{state === 'loading' && <span>Checking image…</span>}{state === 'ok' && <b><CheckCircle2 size={15} /> Ready</b>}</div>;
}

export default function Admin() {
  const [password, setPassword] = useState(() => sessionStorage.getItem('yomsan-admin') || '');
  const [showPassword, setShowPassword] = useState(false);
  const [authenticated, setAuthenticated] = useState(false);
  const [items, setItems] = useState<Vehicle[]>(seedVehicles);
  const [selectedId, setSelectedId] = useState<number | null>(seedVehicles[0]?.id ?? null);
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const selected = items.find(v => v.id === selectedId) ?? items[0];

  const load = async () => { const res = await fetch('/api/vehicles', { cache: 'no-store' }); if (!res.ok) return; const data = await res.json(); if (Array.isArray(data.vehicles)) setItems(data.vehicles); };
  useEffect(() => { load().catch(() => undefined); }, []);

  const login = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setStatus('Checking access…'); try { const res = await fetch('/api/vehicles', { headers: { 'x-admin-password': password } }); const data = await res.json().catch(() => null); if (!res.ok) throw new Error(data?.error || 'Access denied'); sessionStorage.setItem('yomsan-admin', password); setAuthenticated(true); if (Array.isArray(data?.vehicles)) setItems(data.vehicles); setStatus(''); } catch (e) { setStatus(e instanceof Error ? e.message : 'Access denied'); } finally { setBusy(false); } };
  const update = (patch: Partial<Vehicle>) => setItems(current => current.map(v => v.id === selected?.id ? { ...v, ...patch } : v));
  const addVehicle = () => { const id = Math.max(0, ...items.map(v => v.id)) + 1; const next: Vehicle = { id, brand: 'New', model: 'Vehicle', year: 2026, type: 'SUV', status: 'Available', price: 0, mileage: 0, engine: 'Engine', hp: 0, hero: '', gallery: [], colors: [{ name: 'Black', value: '#111111' }], wheels: ['Standard'], interiors: ['Black'] }; setItems([...items, next]); setSelectedId(id); };
  const remove = () => { if (!selected) return; const next = items.filter(v => v.id !== selected.id); setItems(next); setSelectedId(next[0]?.id ?? null); };
  const save = async () => { setBusy(true); setStatus('Saving to Neon…'); try { const res = await fetch('/api/vehicles', { method: 'PUT', headers: { 'content-type': 'application/json', 'x-admin-password': password }, body: JSON.stringify({ vehicles: items }) }); const data = await res.json().catch(() => null); if (!res.ok) throw new Error(data?.error || 'Save failed'); setStatus(`Saved to Neon — ${data.count} vehicles live.`); } catch (e) { setStatus(e instanceof Error ? e.message : 'Save failed'); } finally { setBusy(false); } };
  const setGallery = (value: string) => update({ gallery: [...new Set(value.split('\n').map(s => s.trim()).filter(Boolean))] });
  const galleryUrls = useMemo(() => selected?.gallery || [], [selected?.gallery]);

  if (!authenticated) return <main className="admin-login"><div className="admin-login__box"><p className="admin-kicker">YOMSAN AUTOMOBILE</p><h1>Showroom Admin</h1><p>Manage live inventory stored in Neon.</p><form onSubmit={login}><label>Admin password<div className="admin-password-field"><input autoFocus type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter admin password" autoComplete="current-password" /><button type="button" className="admin-password-toggle" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? 'Hide password' : 'Show password'} title={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><button disabled={busy || !password}>{busy ? 'Checking…' : 'Enter admin'}</button></form>{status && <div className="admin-error">{status}</div>}</div></main>;

  return <main className="admin-shell"><aside className="admin-sidebar"><a href="/" className="admin-back"><ArrowLeft size={16} /> Public showroom</a><div className="admin-brand"><span>Y</span><div><b>YOMSAN</b><small>Neon Inventory Admin</small></div></div><button className="admin-add" onClick={addVehicle}><Plus size={17} /> Add vehicle</button><div className="admin-list">{items.map(v => <button className={v.id === selected?.id ? 'active' : ''} key={v.id} onClick={() => setSelectedId(v.id)}><span>{v.brand}</span><strong>{v.model}</strong><small>{v.status} · ₦{v.price.toLocaleString()}k</small></button>)}</div><button className="admin-logout" onClick={() => { sessionStorage.removeItem('yomsan-admin'); setAuthenticated(false); }}><LogOut size={16} /> Sign out</button></aside>
  <section className="admin-content"><header className="admin-top"><div><p>NEON INVENTORY / {String(items.length).padStart(2, '0')}</p><h1>{selected?.brand} <i>{selected?.model}</i></h1></div><button className="admin-publish" onClick={save} disabled={busy}><Save size={17} /> {busy ? 'Saving…' : 'Save to Neon'}</button></header>
  {selected && <div className="admin-form"><section className="admin-card"><div className="admin-card__head"><div><small>VEHICLE DETAILS</small><h2>Identity & specification</h2></div><button className="danger" onClick={remove}><Trash2 size={15} /> Delete</button></div><div className="field-grid">{[['Brand','brand','text'],['Model','model','text'],['Year','year','number'],['Type','type','text'],['Price (₦ thousands)','price','number'],['Mileage','mileage','number'],['Horsepower','hp','number'],['Engine','engine','text']].map(([label,key,type]) => <label key={key}>{label}<input type={type} value={String((selected as any)[key])} onChange={e => update({ [key]: type === 'number' ? Number(e.target.value) : e.target.value } as Partial<Vehicle>)} /></label>)}<label>Status<select value={selected.status} onChange={e => update({ status: e.target.value as Vehicle['status'] })}><option>Available</option><option>Reserved</option></select></label></div></section>
  <section className="admin-card"><div className="admin-card__head"><div><small>PHOTOGRAPHY</small><h2>Vehicle image manager</h2></div><span className="admin-note">Live preview + validation</span></div><div className="media-manager"><div className="media-hero"><ImagePreview src={selected.hero} label="Hero image" /></div><label>Hero image URL<input value={selected.hero} onChange={e => update({ hero: e.target.value })} placeholder="https://..." /></label><label>Gallery image URLs <small>one URL per line · broken URLs are filtered from the showroom</small><textarea value={selected.gallery.join('\n')} onChange={e => setGallery(e.target.value)} rows={7} placeholder="https://...angle-front.jpg\nhttps://...angle-side.jpg\nhttps://...angle-rear.jpg" /></label><div className="admin-gallery-previews">{galleryUrls.slice(0, 12).map((src, i) => <ImagePreview key={`${src}-${i}`} src={src} label={`Angle ${i + 1}`} />)}</div></div></section>
  <section className="admin-card"><div className="admin-card__head"><div><small>CONFIGURATOR</small><h2>Options shown to customers</h2></div></div><div className="field-grid"><label>Wheels <input value={selected.wheels.join(', ')} onChange={e => update({ wheels: e.target.value.split(',').map(s => s.trim()).filter(Boolean) })} /></label><label>Interiors <input value={selected.interiors.join(', ')} onChange={e => update({ interiors: e.target.value.split(',').map(s => s.trim()).filter(Boolean) })} /></label><label>Exterior colours <input value={selected.colors.map(c => c.name).join(', ')} onChange={e => update({ colors: e.target.value.split(',').map((name, i) => ({ name: name.trim(), value: selected.colors[i]?.value || '#111111' })) })} /></label></div></section></div>}
  {status && <div className="admin-note" style={{ marginTop: 16 }}>{status}</div>}</section></main>;
}
